### ISSUE TITLE
Question: JBehave 5.0 release

### ISSUE THREAD

**Issue by symphony-youri** [jbehave/jbehave-core#29]
Hello,

I just wanted to know if there was a plan to release the version 5 soon.
The performance improvements on the step collections are quite interesting.

Thanks,

**Comment by pzygielo** [comment]
I second this.
It would be great to see JBEHAVE-1479 released.

**Comment by maurotalevi** [comment]
Yes, 5.0 is coming out in a few days, certainly by the end of the month.

**Comment by valfirst** [comment]
@symphony-youri, @pzygielo JBehave 5.0 is released

**Comment by valfirst** [comment]
Also please find migration paths here: https://jbehave.org/reference/preview/migration-paths.html
